version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_serasa
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: serasa-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network

  app:
    build: .
    container_name: nest_app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres_serasa:5432/serasa-db?schema=public" 
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    command: npm run start:dev

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local